# Generated by Django 4.1.4 on 2023-01-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Обьявление', 'verbose_name_plural': 'Обьявления'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
